---
server:
  port:

spring:
  datasource:
    url: jdbc:postgresql://localhost/task-tracker
    username: postgres
    password: egorick
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update